### ISSUE TITLE
#1. 브랜치 생성으로 환경셋팅 성공했으나, gitignore 되지 않는 현상

### ISSUE THREAD

**Issue by jiwon709** [chanhong-jiwon-project/auto-commit-project#3]
*생성해 둔 PR 참고   
mac -> window OS 환경변경으로 인해 환경셋팅이 제대로 이루어지지 않아,   
임시용 브랜치 생성 후, gitignore 안의 파일들을 주석처리하여 push, pull 과정 진행.   
   
환경셋팅에 성공했으나, 추후에 dev 및 master 브랜치에 merge 할 경우,   
gitignore 되어야 할 파일들이 같이 merge 되는 현상 예상.   
새로운 브랜치 생성하여 새로 PR 생성하였으나, 똑같은 현상 발생.   

어떻게 해야하지..?
```
1. 현재 머지된 브랜치 삭제 -> dev 브랜치에서 다시 생성 (window 그냥 포기하고 mac에서 개발할지, directory 압축하여 옮길지)
2. window 에서 프로젝트 재생성 (재생성하면 기존 프로젝트와 겹쳐서 git clone이 안 됨. 수작업으로 로직 복붙, 붙여넣기?)
```

**Comment by chanhong-dev** [comment]
파일 삭제 후 다시 생성할 때 git 관리 파일로 등록 안하는 방법이 제일 간단할 것 같아

**Comment by chanhong-dev** [comment]
OS 변경으로 인한 프로젝트 세팅이 안되는 경우를 격어보지 못해서 솔직히 어떤 상황인지 아직 잘 모르겠어

**Comment by jiwon709** [comment]
머지해도 상관은 없는 파일들이나, 지저분해지므로 두 브랜치 삭제 후 , dev 브랜치로 다시 pull  진행 .
